# Site settings
title: SaraiPe
email: 210300271@ucaribe.edu.mx
url: https://github.com/SaraiPech/SaraiPech.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: "/grayscale-theme"

# Color settings
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SaraiPechEk?t=kxHodaun1-2tPXndMQwXPQ&s=09
  - title: facebook
    url: https://www.facebook.com/Sarai.pech.ek
  - title: instagram
    url: https://www.instagram.com/saraai.sin.h/
  - title: github
    url: https://github.com/SaraiPech

# Build settings
markdown: kramdown
permalink: pretty
